name: python 3.6
channels:
  - conda-forge
dependencies:
  - python=3.6
  - slycot==0.4.0.0
  - lxml==4.5.0
  - pandas==0.25.3
  - xlrd==1.1.0
  - networkx==2.4
  - control==0.8.3
  - orderedset==2.0.3
  - pip
  - pip:
    - quadprog==0.1.8
    - svgpathtools==1.3.3
    - cobra==0.14.2
    - BondGraphTools==0.3.7
