name: python 3.6
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - sympy
  - lxml
  - pandas
  - xlrd
  - networkx
  - pip
  - pip:
    - svgpathtools
    - datetime
    - cobra
    - BondGraphTools==0.3.7

