name: python 3.6
dependencies:
  - python=3.6
  - matplotlib
  - lxml
  - pandas
  - xlrd
  - networkx
  - control
  - pip
  - pip:
    - svgpathtools
    - datetime
    - cobra
    - BondGraphTools

